title = 'blog of axlefublr'
base_url = 'https://axlefublr.github.io'
generate_feeds = true
feed_filenames = ['rss.xml']
hard_link_static = true
author = 'Axlefublr'
build_search_index = false

[markdown]
external_links_target_blank = true # opens external links in a new tab always (this is to make my readers actually remember about finishing reading my blog, lol)

[markdown.highlighting]
theme = 'gruvbox-material'
style = 'inline'
extra_themes = ['theme.json']
